# Generated by Django 5.0 on 2023-12-20 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='ownerLikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ownlikes', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pets.category'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='likes',
            name='petsLikes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pets.mypets', verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='posts',
            name='petsPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='pets.mypets', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='pets.posts'),
        ),
    ]
